apiVersion: v1
kind: ConfigMap
metadata: {name: taskboard-config}
data:
  DATABASE_URL: postgresql+psycopg://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:5432/{{ .Values.database.name }}
---
apiVersion: v1
kind: Secret
metadata: {name: taskboard-db}
type: Opaque
stringData: {POSTGRES_PASSWORD: {{ .Values.database.password | quote }}}
